# Generated by Django 2.2 on 2020-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tech', 'Бытовая техника'), ('other', 'Разное'), ('food', 'Еда'), ('tools', 'Инструменты'), ('toys', 'Игрушки')], default='other', max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('3', 'Хороший товар'), ('1', 'Очень плохой товар'), ('5', 'Отличный товар'), ('2', 'Плохой товар'), ('4', 'Очень хороший товар')], max_length=2, verbose_name='Оценка'),
        ),
    ]
